### ISSUE TITLE
Readme file may contain typos

### ISSUE THREAD

**Issue by SuperYYT** [Infixo/CS2-RealPop#1]
9 years? 6 years? Is this true or a mistake?
![%7B1DFBA21F-05F7-4557-84BA-E81FAC1D62FA%7D](https://github.com/Infixo/CS2-RealPop/assets/19758904/b2abf9f6-4d16-446a-a44d-f15a5383b654)

**Comment by Infixo** [comment]
That is a bit complicated. Anyway, no longer matters as in v0.3 this is changed.
There is "Average time to graduation" displayed for a school. It was misleading because values were like 0.5 or 0.7 days. This UI converts days to YEARS and 0.5 is displayed as 6 months. It is misleading because cims don't stay in school for 6 months (aka days) nor 9. They stay 1-2 days.
Anyway, I revamped this logic totally. Now UI shows good info which is aligned with actual time spent in schools.
