### ISSUE TITLE
Death Issue with latest update v0.7.0

### ISSUE THREAD

**Issue by Koolkat17** [Infixo/CS2-RealPop#10]
Just wanted to let ya know this happened after I updated to the latest version. The city is nothing special but pretty much every area on the map with population suddenly had a large amount of deaths. Hope the Screen Grab helps.
![Screenshot 2024-02-19 193340](https://github.com/Infixo/CS2-RealPop/assets/99687274/40d92a1c-18da-454f-ad05-5ccada631430)

**Comment by jetcz** [comment]
Same here. In 200k city I need like 30+ crematoriums to deal with all the dead people... I get that the vanilla system wasn't realistic, but this isn't either really. In vanilla, I had about 1.5k deaths/month, with this mod it spiked to 10k and then stabilized on about 6k which is still way too much in my opinion.

**Comment by Infixo** [comment]
There is no bug. Please read about Death process. I specifically put warnings that there will be more deaths.

**Comment by Infixo** [comment]
@jetcz In 200k city with PopRebalance mod there should be approx. 25% children and teens, 60% adults and 15% seniors. 60% Adults is 120k people. Adults are spread in 50 years life span, so on average 2400 per year. 
This means 2400 people are becoming Seniors every day in your. City. So 2400 needs to die every day to have stable population.

**Comment by Infixo** [comment]
@jetcz However, if your population has different structure, then e.g. you may have more Adults or more Seniors then it will be much more than 2400

**Comment by Infixo** [comment]
@jetcz example. If you have 25% seniors, then your death rate will be much, much higher because they will die more frequently to reach that 15% balance, and it takes several days to stabilize.

**Comment by Infixo** [comment]
Anyway, it would be easier to analyze if you post Demographics from InfoLoom.

**Comment by Koolkat17** [comment]
> There is no bug. Please read about Death process. I specifically put warnings that there will be more deaths.

Sorry about that completely my fault. I didn't read the Changelog close enough. I just disabled the Mod and it did stabilize after a few in game days.  Any plans to have in an in game menu to adjust the settings or just the Config file? Anyways thanks for getting back to me I usually read the updates version changelog much closer.

**Comment by jetcz** [comment]
@Infixo I left the simulation run for a whole ingame year and it stabilised on about 6k deaths/month
![image](https://github.com/Infixo/CS2-RealPop/assets/8216033/8973870f-1a13-4888-aa07-e3a68a164104)

I'm not disputing that your mod actually makes the simulation more realistic with the age distribution and peoples lifespan, but I'm not entirely sure the current state of the game can handle it.

My (limited) understanding of the simulation is that when you have a city of 200k, then only a certain portion of those can be active agents and other game mechanics account for this, so other aspects of the simulation kind of automagically work even if not serviced by an agent. Eg. you never see a cim to go to school, they just "appear" there automatically, same goes for shopping, cims can actually satisfy their shopping needs without ever leaving the house and become an active agent, etc.

What I'm trying to say is that it does not seem the death care is designed that way? It feels like every death needs to be serviced by an agent (hearse), is it true?
I would expect that some of the deaths won't need transportation to crematoriums and just magically appear there, or that the cim will just dissapear from the city without acually needing any deathcare, to be inline with the rest of the "shortcuts" the simulation does.

**Comment by Infixo** [comment]
> > There is no bug. Please read about Death process. I specifically put warnings that there will be more deaths.
> 
> Sorry about that completely my fault. I didn't read the Changelog close enough. I just disabled the Mod and it did stabilize after a few in game days. Any plans to have in an in game menu to adjust the settings or just the Config file? Anyways thanks for getting back to me I usually read the updates version changelog much closer.

You may turn off the new death process, and just use vanilla approach.
The param values in the mod are not intended to be changed very often or during the game, they are related to processes taking long time. As for now for testing and experimenting the config file is enough. Maybe in the future when full modding support will be available, I will add some UI, but for now I'd rather spend more time on enhancing features and balancing the mod.

**Comment by Infixo** [comment]
@jetcz Very good points you are raising, I appreciate the insight.

What you say is ofc true - the dead bodies must be collected and there is no teleportation to crematorium or bodies just disappearing. For reference, in CS1 the bodies did disappear. So why CO did not implement that in CS2? Also, there is no "agent scaling" anywhere in the DeathSystem or related systems (Deathcare). Again - why did CO not implement this failsafe?

The answer is very simple - because in CS2 people die VERY RARELY. Idk it this is just an affect of many imbalances, or by design. The fact is that seniors mostly LEAVE city due to rent problems. Whoever stays long enough to get to the dying age (which is 108 days) then actually dies within 12 days. There are really, really not many seniors in the city that are able to stay this long.

**Comment by Infixo** [comment]
@jetcz PopRebalance make the city actually behave realistically. And yes, more agents spawn to get the bodies. Agents meaning hearseys. I'd say a "vanishing body" mechanism would be helpful.
I need to research how difficult it would be to make it, so I cannot promise anything yet.

**Comment by jetcz** [comment]
@Infixo thank you for your effort!
Idea: in developer options you can trigger "sudden death" event on a cim and they just vanish into thin air, no death care needed. Could that be an option perhaps?

**Comment by Infixo** [comment]
> @Infixo thank you for your effort! Idea: in developer options you can trigger "sudden death" event on a cim and they just vanish into thin air, no death care needed. Could that be an option perhaps?

Well, it may help with understanding how to vanish a corpse, because I assume they do that. I more or less know how to do that, but an example from CO would be helpful. That would allow me to introduce similar mechanics as in CS1 where some corpses just vanished.
I personally like more realism but seems that many people are scared by too many death warnings xD

**Comment by jetcz** [comment]
@Infixo great job!!
One little thing, I wanted to experiment with the config values but I don't have the config file created under bepinex folder, what I'm I doing wrong? I'm using Thunderstore mod manager, if that makes any difference.

**Comment by Infixo** [comment]
> @Infixo great job!!
> 
> One little thing, I wanted to experiment with the config values but I don't have the config file created under bepinex folder, what I'm I doing wrong? I'm using Thunderstore mod manager, if that makes any difference.

The config should be in BepInEx/config. Could be that I forgot to add subfolder name, sorry.

**Comment by Infixo** [comment]
@jetcz Ok, the info is there... you probably missed it...

### Installation
1. Place the `RealPop.dll` file in your BepInEx `Plugins` folder.
2. The config file is automatically created (in BepInEx\config) when the game is run once.

**Comment by jetcz** [comment]
@Infixo turns out if you use Thunderstore manager, the folder nor config file never appears on the filesystem, you have to edit it via the Thunderstore manager where there is a section for such configs, I didn't know that.
Anyway, interesting thing is when I set the vanish chance to 100% it results in significant increase in population and residental demand. I find a value of 65% optimal.
Anyway, thank you so much for your time and effort to make CS2 playable!
