### ISSUE TITLE
Highly Educated cims at the begining of the game

### ISSUE THREAD

**Issue by Infixo** [Infixo/CS2-RealPop#12]
Well and Highly educated cims at the begining are a bit of inconvenience.

Options.
1. Adjust to game progress like when University is available.
2. Adjust to general population.
3. Adjust to actual job openings.

Option 3 should be pretty easy. There is a counting system implemented for InfoViewUI maybe it can be reused.
Also, it a good story - cims come to look for a job, so it make sense that Well Edu would come only when Well Edu openings exist.

**Comment by Kalmorph** [comment]
Can confirm this behavious, when **starting a new game** with this mod ON, the game will balance the education between all citizens, which lead to several issues, specially with contant low residential demands and no medium/high density population. Low commercials also are constant demanded, but ocasionally have _Lack of Labor issues_, because they don't have enough low Uneducated citizens to fill all jobs, they prefer to just open their own businesses.

**Comment by Infixo** [comment]
> Can confirm this behavious, when **starting a new game** with this mod ON, the game will balance the education between all citizens, which lead to several issues, specially with contant low residential demands and no medium/high density population. Low commercials also are constant demanded, but ocasionally have _Lack of Labor issues_, because they don't have enough low Uneducated citizens to fill all jobs, they prefer to just open their own businesses.

Not all you write about is caused by the fact that some cims that come are well and highly educated.
Especially residential demand is not related to what cims are coming - it is based on empty homes.
Cims will always choose Low Res because of Spacious Homes, stop building Low Res, let them take all homes and then they will start setting in Med and High res.
Also, if you build too much shops then there will be lack of workers... don't try to fullfill Commercial Demand, it only leads to overinvesting
